# This is a basic workflow to help you get started with Actions
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
    - main
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev 
    defaults:
      run:
         shell: bash
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
         tf_actions_version: 1.1.8
         tf_actions_subcommand: 'init'
         tf_actions_working_dir: "./terraform"
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
         tf_actions_version: 1.1.8
         tf_actions_subcommand: 'validate'
         tf_actions_working_dir: "./Terraform"     
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
         tf_actions_version: 1.1.8
         tf_actions_subcommand: 'plan'
         tf_actions_working_dir: "./terraform"
      - name: 'Terraform Apply'
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
         tf_actions_version: 1.1.8
         tf_actions_subcommand: 'apply'
         tf_actions_working_dir: "./terraform"
  sonarback:
    name: test backend
    runs-on: ubuntu-latest
    needs: terraform
    steps:
     - name: test backend
       run: |
         echo "test backend"
         sleep 10s
     - uses: convictional/trigger-workflow-and-wait@v1.6.3
       with:
          owner: khalilbou97
          repo: backendpfe
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: build.yml
          ref: master
     - name: Deploy back
       run: |
         echo "Deploy back"
         sleep 10s
  sonarfront:
    name: test frontend
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: test frontend
        run: |
          echo "test frontend"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: khalilbou97
          repo: Siruis-RH-Front
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: build.yml
          ref: main
      - name: test front
        run: |
          echo "test front"
          sleep 10s
  backend:
    name: deploy backend
    runs-on: ubuntu-latest
    needs: sonarback
    steps:
      - name: Deploy backend
        run: |
          echo "deploy backend"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: khalilbou97
          repo: siruis-HR
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: master_backendpfesiriusrh.yml
          ref: master
      - name: Deploy back
        run: |
          echo "Deploy back"
          sleep 10s
  frontend:
    name: deploy frontend
    runs-on: ubuntu-latest
    needs: sonarfront
    steps:
      - name: Deploy frontend
        run: |
          echo "deploy frontend"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: khalil97
          repo: front
          github_token: ${{ secrets.G_ACCESS_TOKEN }}
          workflow_file_name: master_frontendsiriusrh.yml
          ref: master
      - name: Deploy front
        run: |
          echo "Deploy front"
          sleep 10s
